[theme]
base                   = "light"
primaryColor           = "#C1C0D5"
backgroundColor        = "#DAC7DB"
secondaryBackgroundColor = "#F2E8F1"
textColor              = "#000000"
font                   = "sans serif"
